import type {
  User,
  Project,
  Agent,
  SEOAudit,
  ContentPiece,
  SocialMonitor,
  KeywordData,
  AnalyticsData,
  Notification,
  Workflow,
} from '@/types'

export const mockUser: User = {
  id: '1',
  email: 'founder@startup.com',
  name: 'Alex Founder',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  role: 'admin',
  plan: 'pro',
  createdAt: '2024-01-15T00:00:00Z',
}

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'SaaS Dashboard',
    url: 'https://saasdashboard.io',
    description: 'Analytics dashboard for SaaS businesses',
    status: 'active',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-05-10T00:00:00Z',
    metrics: {
      totalTraffic: 45200,
      organicTraffic: 28500,
      backlinks: 1240,
      domainAuthority: 42,
      pageAuthority: 38,
      keywordRankings: 156,
      socialEngagement: 8900,
      conversionRate: 3.2,
    },
  },
  {
    id: '2',
    name: 'DevTools Pro',
    url: 'https://devtools.pro',
    description: 'Developer productivity tools suite',
    status: 'active',
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-05-09T00:00:00Z',
    metrics: {
      totalTraffic: 31200,
      organicTraffic: 19800,
      backlinks: 890,
      domainAuthority: 38,
      pageAuthority: 35,
      keywordRankings: 98,
      socialEngagement: 5600,
      conversionRate: 2.8,
    },
  },
]

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'SEO Audit Agent',
    type: 'seo-audit',
    status: 'running',
    description: 'Comprehensive website SEO analysis',
    icon: 'Search',
    lastRun: '2024-05-10T14:30:00Z',
    nextRun: '2024-05-11T14:30:00Z',
    frequency: 'daily',
    projectId: '1',
    config: { depth: 'comprehensive', pages: 100 },
    results: [],
    metrics: {
      tasksCompleted: 156,
      successRate: 98.5,
      avgExecutionTime: 245,
      impactScore: 87,
    },
  },
  {
    id: '2',
    name: 'GEO Optimizer',
    type: 'geo-optimization',
    status: 'completed',
    description: 'Optimize for AI search engines',
    icon: 'Brain',
    lastRun: '2024-05-10T12:00:00Z',
    nextRun: '2024-05-11T12:00:00Z',
    frequency: 'daily',
    projectId: '1',
    config: { platforms: ['chatgpt', 'claude', 'perplexity'] },
    results: [],
    metrics: {
      tasksCompleted: 89,
      successRate: 95.2,
      avgExecutionTime: 180,
      impactScore: 92,
    },
  },
  {
    id: '3',
    name: 'Content Writer',
    type: 'content-writer',
    status: 'idle',
    description: 'AI-powered content generation',
    icon: 'PenTool',
    lastRun: '2024-05-09T16:00:00Z',
    nextRun: '2024-05-11T10:00:00Z',
    frequency: 'weekly',
    projectId: '1',
    config: { tone: 'professional', length: 'medium' },
    results: [],
    metrics: {
      tasksCompleted: 234,
      successRate: 99.1,
      avgExecutionTime: 320,
      impactScore: 85,
    },
  },
  {
    id: '4',
    name: 'Reddit Monitor',
    type: 'reddit-monitor',
    status: 'running',
    description: 'Track Reddit mentions and opportunities',
    icon: 'MessageSquare',
    lastRun: '2024-05-10T15:00:00Z',
    nextRun: '2024-05-10T16:00:00Z',
    frequency: 'hourly',
    projectId: '1',
    config: { subreddits: ['startups', 'SaaS', 'marketing'] },
    results: [],
    metrics: {
      tasksCompleted: 1200,
      successRate: 97.8,
      avgExecutionTime: 45,
      impactScore: 78,
    },
  },
  {
    id: '5',
    name: 'Hacker News Monitor',
    type: 'hackernews-monitor',
    status: 'completed',
    description: 'Monitor HN discussions',
    icon: 'Terminal',
    lastRun: '2024-05-10T13:00:00Z',
    nextRun: '2024-05-10T14:00:00Z',
    frequency: 'hourly',
    projectId: '1',
    config: { keywords: ['SaaS', 'analytics', 'developer tools'] },
    results: [],
    metrics: {
      tasksCompleted: 450,
      successRate: 96.5,
      avgExecutionTime: 30,
      impactScore: 82,
    },
  },
  {
    id: '6',
    name: 'X/Twitter Monitor',
    type: 'twitter-monitor',
    status: 'paused',
    description: 'Track X mentions and trends',
    icon: 'Twitter',
    lastRun: '2024-05-08T10:00:00Z',
    nextRun: '2024-05-11T10:00:00Z',
    frequency: 'daily',
    projectId: '1',
    config: { hashtags: ['#SaaS', '#buildinpublic', '#indiehacker'] },
    results: [],
    metrics: {
      tasksCompleted: 890,
      successRate: 94.3,
      avgExecutionTime: 60,
      impactScore: 75,
    },
  },
  {
    id: '7',
    name: 'Competitor Analysis',
    type: 'competitor-analysis',
    status: 'idle',
    description: 'Analyze competitor strategies',
    icon: 'Target',
    lastRun: '2024-05-07T09:00:00Z',
    nextRun: '2024-05-14T09:00:00Z',
    frequency: 'weekly',
    projectId: '1',
    config: { competitors: ['competitor1.com', 'competitor2.com'] },
    results: [],
    metrics: {
      tasksCompleted: 67,
      successRate: 100,
      avgExecutionTime: 480,
      impactScore: 90,
    },
  },
  {
    id: '8',
    name: 'Keyword Research',
    type: 'keyword-research',
    status: 'running',
    description: 'Discover high-value keywords',
    icon: 'Key',
    lastRun: '2024-05-10T15:30:00Z',
    nextRun: '2024-05-11T15:30:00Z',
    frequency: 'daily',
    projectId: '1',
    config: { region: 'US', language: 'en' },
    results: [],
    metrics: {
      tasksCompleted: 345,
      successRate: 99.5,
      avgExecutionTime: 120,
      impactScore: 88,
    },
  },
]

export const mockSEOAudit: SEOAudit = {
  id: '1',
  projectId: '1',
  timestamp: '2024-05-10T14:30:00Z',
  overallScore: 78,
  categories: [
    { name: 'On-Page SEO', score: 85, weight: 25, status: 'good' },
    { name: 'Technical SEO', score: 72, weight: 25, status: 'warning' },
    { name: 'Content Quality', score: 80, weight: 20, status: 'good' },
    { name: 'User Experience', score: 75, weight: 15, status: 'warning' },
    { name: 'Mobile Optimization', score: 82, weight: 15, status: 'good' },
  ],
  issues: [
    {
      id: '1',
      category: 'Technical SEO',
      severity: 'critical',
      title: 'Missing XML Sitemap',
      description: 'Your website is missing an XML sitemap, making it harder for search engines to discover all pages.',
      url: '/sitemap.xml',
      fix: 'Generate and submit an XML sitemap to Google Search Console',
      impact: 'high',
    },
    {
      id: '2',
      category: 'Technical SEO',
      severity: 'critical',
      title: 'Slow Page Speed (LCP > 4s)',
      description: '12 pages have a Largest Contentful Paint exceeding 4 seconds.',
      url: '/blog/featured',
      fix: 'Optimize images, implement lazy loading, and reduce JavaScript execution time',
      impact: 'high',
    },
    {
      id: '3',
      category: 'On-Page SEO',
      severity: 'warning',
      title: 'Missing Meta Descriptions',
      description: '23 pages are missing meta descriptions.',
      fix: 'Write compelling meta descriptions for all pages (150-160 characters)',
      impact: 'medium',
    },
    {
      id: '4',
      category: 'On-Page SEO',
      severity: 'warning',
      title: 'Duplicate Title Tags',
      description: '8 pages have duplicate or very similar title tags.',
      fix: 'Create unique, descriptive title tags for each page',
      impact: 'medium',
    },
    {
      id: '5',
      category: 'Content Quality',
      severity: 'warning',
      title: 'Thin Content Pages',
      description: '15 pages have less than 300 words of content.',
      fix: 'Expand content with valuable information, add multimedia elements',
      impact: 'medium',
    },
    {
      id: '6',
      category: 'User Experience',
      severity: 'info',
      title: 'Missing Breadcrumb Navigation',
      description: 'Breadcrumb navigation is not implemented on product pages.',
      fix: 'Add structured breadcrumb navigation with schema markup',
      impact: 'low',
    },
  ],
  recommendations: [
    {
      id: '1',
      priority: 1,
      category: 'Technical SEO',
      title: 'Implement Core Web Vitals Optimization',
      description: 'Focus on improving LCP, FID, and CLS metrics across all key pages.',
      expectedImpact: '+15-25% organic traffic',
      difficulty: 'hard',
      estimatedTime: '2-3 weeks',
    },
    {
      id: '2',
      priority: 2,
      category: 'Content',
      title: 'Create Pillar Content Strategy',
      description: 'Develop 5 comprehensive pillar pages with supporting cluster content.',
      expectedImpact: '+30-50% keyword rankings',
      difficulty: 'medium',
      estimatedTime: '4-6 weeks',
    },
    {
      id: '3',
      priority: 3,
      category: 'On-Page SEO',
      title: 'Optimize Internal Linking Structure',
      description: 'Implement strategic internal linking to distribute link equity effectively.',
      expectedImpact: '+10-20% page authority',
      difficulty: 'easy',
      estimatedTime: '1 week',
    },
  ],
  competitors: [
    { domain: 'competitor1.com', authority: 58, backlinks: 3400, keywords: 890, traffic: 78000, overlap: 34 },
    { domain: 'competitor2.com', authority: 52, backlinks: 2100, keywords: 650, traffic: 54000, overlap: 28 },
    { domain: 'competitor3.com', authority: 45, backlinks: 1500, keywords: 420, traffic: 32000, overlap: 22 },
  ],
}

export const mockContentPieces: ContentPiece[] = [
  {
    id: '1',
    projectId: '1',
    title: 'The Complete Guide to SaaS Analytics Dashboards',
    type: 'blog',
    status: 'published',
    content: '# The Complete Guide to SaaS Analytics Dashboards\n\nIn today\'s data-driven world...',
    seoScore: 92,
    readabilityScore: 78,
    keywords: ['saas analytics', 'dashboard design', 'metrics tracking'],
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-05-05T14:00:00Z',
    publishedAt: '2024-05-05T14:00:00Z',
    engagement: {
      views: 4520,
      clicks: 890,
      shares: 234,
      comments: 67,
      avgTimeOnPage: 245,
    },
  },
  {
    id: '2',
    projectId: '1',
    title: '10 Metrics Every SaaS Founder Should Track',
    type: 'blog',
    status: 'published',
    content: '# 10 Metrics Every SaaS Founder Should Track\n\nTracking the right metrics...',
    seoScore: 88,
    readabilityScore: 82,
    keywords: ['saas metrics', 'founder guide', 'kpi tracking'],
    createdAt: '2024-04-20T09:00:00Z',
    updatedAt: '2024-04-25T11:00:00Z',
    publishedAt: '2024-04-25T11:00:00Z',
    engagement: {
      views: 3890,
      clicks: 720,
      shares: 189,
      comments: 45,
      avgTimeOnPage: 198,
    },
  },
  {
    id: '3',
    projectId: '1',
    title: 'How to Reduce Churn by 30% with Better Analytics',
    type: 'blog',
    status: 'review',
    content: '# How to Reduce Churn by 30% with Better Analytics\n\nCustomer churn is the silent killer...',
    seoScore: 85,
    readabilityScore: 75,
    keywords: ['churn reduction', 'customer retention', 'analytics'],
    createdAt: '2024-05-08T13:00:00Z',
    updatedAt: '2024-05-10T10:00:00Z',
  },
  {
    id: '4',
    projectId: '1',
    title: 'LinkedIn Post: Why We Built Our Own Analytics',
    type: 'social',
    status: 'draft',
    content: 'After trying 15 different analytics tools, we decided to build our own...',
    seoScore: 0,
    readabilityScore: 88,
    keywords: ['linkedin', 'analytics', 'startup'],
    createdAt: '2024-05-10T16:00:00Z',
    updatedAt: '2024-05-10T16:00:00Z',
  },
]

export const mockSocialMonitor: SocialMonitor = {
  id: '1',
  platform: 'reddit',
  projectId: '1',
  keywords: ['saas analytics', 'dashboard tools', 'startup metrics'],
  mentions: [
    {
      id: '1',
      platform: 'reddit',
      url: 'https://reddit.com/r/startups/comments/abc123',
      title: 'What analytics dashboard do you use for your SaaS?',
      content: 'I\'m looking for a good analytics dashboard for my SaaS startup...',
      author: 'startup_founder_42',
      upvotes: 234,
      comments: 89,
      sentiment: 'positive',
      timestamp: '2024-05-10T12:00:00Z',
      relevance: 95,
    },
    {
      id: '2',
      platform: 'reddit',
      url: 'https://reddit.com/r/SaaS/comments/def456',
      title: 'Show HN: Built an analytics dashboard in 2 weeks',
      content: 'Just launched my analytics dashboard for SaaS businesses...',
      author: 'indie_dev_99',
      upvotes: 567,
      comments: 123,
      sentiment: 'neutral',
      timestamp: '2024-05-09T15:00:00Z',
      relevance: 88,
    },
    {
      id: '3',
      platform: 'reddit',
      url: 'https://reddit.com/r/marketing/comments/ghi789',
      title: 'Best tools for tracking marketing metrics?',
      content: 'Need recommendations for comprehensive marketing analytics...',
      author: 'marketing_pro',
      upvotes: 156,
      comments: 67,
      sentiment: 'positive',
      timestamp: '2024-05-08T10:00:00Z',
      relevance: 82,
    },
  ],
  trending: [
    { topic: 'AI-powered analytics', volume: 2340, growth: 45, sentiment: 0.72, relatedKeywords: ['AI analytics', 'machine learning dashboard'] },
    { topic: 'Real-time metrics', volume: 1890, growth: 32, sentiment: 0.68, relatedKeywords: ['live dashboard', 'real-time tracking'] },
    { topic: 'Customer churn analysis', volume: 1560, growth: 28, sentiment: 0.55, relatedKeywords: ['retention metrics', 'churn prediction'] },
  ],
  sentiment: {
    positive: 62,
    neutral: 28,
    negative: 10,
    overall: 0.72,
    trend: 'up',
  },
}

export const mockKeywords: KeywordData[] = [
  { keyword: 'saas analytics dashboard', volume: 2400, difficulty: 45, cpc: 8.5, currentPosition: 3, previousPosition: 5, trend: 'up', intent: 'commercial', serpFeatures: ['featured_snippet', 'people_also_ask'] },
  { keyword: 'analytics dashboard tools', volume: 1800, difficulty: 38, cpc: 6.2, currentPosition: 5, previousPosition: 7, trend: 'up', intent: 'commercial', serpFeatures: ['shopping_results'] },
  { keyword: 'startup metrics tracking', volume: 1200, difficulty: 32, cpc: 4.8, currentPosition: 2, previousPosition: 2, trend: 'stable', intent: 'informational', serpFeatures: ['featured_snippet'] },
  { keyword: 'customer churn analysis', volume: 900, difficulty: 28, cpc: 5.5, currentPosition: 8, previousPosition: 12, trend: 'up', intent: 'informational', serpFeatures: [] },
  { keyword: 'saas kpis dashboard', volume: 750, difficulty: 25, cpc: 3.2, currentPosition: 4, previousPosition: 6, trend: 'up', intent: 'commercial', serpFeatures: ['people_also_ask'] },
  { keyword: 'revenue analytics platform', volume: 600, difficulty: 42, cpc: 9.1, currentPosition: 11, previousPosition: 15, trend: 'up', intent: 'transactional', serpFeatures: [] },
  { keyword: 'product analytics tools', volume: 3200, difficulty: 52, cpc: 7.8, currentPosition: 9, previousPosition: 8, trend: 'down', intent: 'commercial', serpFeatures: ['shopping_results', 'people_also_ask'] },
  { keyword: 'growth metrics software', volume: 450, difficulty: 20, cpc: 2.5, currentPosition: 1, previousPosition: 3, trend: 'up', intent: 'commercial', serpFeatures: ['featured_snippet'] },
]

export const generateAnalyticsData = (days = 30): AnalyticsData[] => {
  const data: AnalyticsData[] = []
  const now = new Date()
  for (let i = days - 1; i >= 0; i--) {
    const date = new Date(now)
    date.setDate(date.getDate() - i)
    const baseTraffic = 1500 + Math.sin(i * 0.2) * 300
    const organic = Math.floor(baseTraffic * 0.65 + Math.random() * 200)
    const direct = Math.floor(baseTraffic * 0.15 + Math.random() * 100)
    const referral = Math.floor(baseTraffic * 0.12 + Math.random() * 80)
    const social = Math.floor(baseTraffic * 0.08 + Math.random() * 60)
    data.push({
      date: date.toISOString().split('T')[0],
      traffic: organic + direct + referral + social,
      organic,
      direct,
      referral,
      social,
      conversions: Math.floor((organic + direct) * 0.032),
      revenue: Math.floor((organic + direct) * 0.032 * 49),
      bounceRate: 35 + Math.random() * 15,
      avgSessionDuration: 120 + Math.random() * 180,
    })
  }
  return data
}

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'success',
    title: 'SEO Audit Complete',
    message: 'Your weekly SEO audit has completed. Overall score: 78/100',
    timestamp: '2024-05-10T14:30:00Z',
    read: false,
    action: { label: 'View Report', url: '/seo-audit' },
  },
  {
    id: '2',
    type: 'warning',
    title: 'Keyword Ranking Drop',
    message: '"product analytics tools" dropped from #8 to #9',
    timestamp: '2024-05-10T12:00:00Z',
    read: false,
    action: { label: 'View Details', url: '/keywords' },
  },
  {
    id: '3',
    type: 'info',
    title: 'New Reddit Mention',
    message: 'Your product was mentioned in r/startups (234 upvotes)',
    timestamp: '2024-05-10T10:00:00Z',
    read: true,
    action: { label: 'View Thread', url: '/social' },
  },
  {
    id: '4',
    type: 'success',
    title: 'Content Published',
    message: '"The Complete Guide to SaaS Analytics" is now live',
    timestamp: '2024-05-09T16:00:00Z',
    read: true,
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: '1',
    name: 'Weekly SEO Maintenance',
    description: 'Run SEO audit, fix critical issues, and update sitemap',
    agents: ['1', '11'],
    trigger: 'scheduled',
    schedule: '0 9 * * 1',
    status: 'active',
    lastRun: '2024-05-06T09:00:00Z',
    nextRun: '2024-05-13T09:00:00Z',
    runs: [
      { id: 'r1', status: 'completed', startedAt: '2024-05-06T09:00:00Z', completedAt: '2024-05-06T09:45:00Z', results: {} },
      { id: 'r2', status: 'completed', startedAt: '2024-04-29T09:00:00Z', completedAt: '2024-04-29T09:38:00Z', results: {} },
    ],
  },
  {
    id: '2',
    name: 'Content & Distribution Pipeline',
    description: 'Generate blog post, optimize for SEO, and distribute to social channels',
    agents: ['3', '4', '5', '6'],
    trigger: 'scheduled',
    schedule: '0 10 * * 3',
    status: 'active',
    lastRun: '2024-05-08T10:00:00Z',
    nextRun: '2024-05-15T10:00:00Z',
    runs: [
      { id: 'r3', status: 'completed', startedAt: '2024-05-08T10:00:00Z', completedAt: '2024-05-08T11:30:00Z', results: {} },
    ],
  },
  {
    id: '3',
    name: 'Competitor Intelligence',
    description: 'Analyze competitors and update keyword strategy',
    agents: ['7', '8'],
    trigger: 'scheduled',
    schedule: '0 8 * * 1',
    status: 'paused',
    lastRun: '2024-04-22T08:00:00Z',
    nextRun: '2024-04-29T08:00:00Z',
    runs: [],
  },
]
